version: "3"
services:
    zookeeper:
      image: debezium/zookeeper:latest
      container_name: zookeeper
      ports:
         - 2181:2181
         - 2888:2888
         - 3888:3888
      networks:
         - hadoopnet
      depends_on:
         - namenode
         - datanode
      restart: always
    namenode:
      image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
      container_name: namenode
      ports:
         - 50070:50070
         - 9020:8020
      networks:
         - hadoopnet
      volumes:
         - hadoop_namenode:/hadoop/dfs/name
      environment:
         - CLUSTER_NAME=test
#      env_file:
#         - ./hadoop.env
      restart: always
    datanode:
      image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
      container_name: datanode1
      networks:
         - hadoopnet
      ports:
         - 50075:50075
      depends_on:
         - namenode
      volumes:
         - hadoop_datanode:/hadoop/dfs/data
      environment:
         SERVICE_PRECONDITION: “namenode:9870"
 #     env_file:
 #        - ./hadoop.env
      restart: always
    historyserver:
      image: bde2020/hadoop-historyserver:1.1.0-hadoop2.7.1-java8
      container_name: historyserver
      restart: always
      environment:
         SERVICE_PRECONDITION: “namenode:8020 namenode:9870 datanode:9864”
      volumes:
         - hadoop_historyserver:/hadoop/yarn/timeline
#      env_file:
#         - ./hadoop.env
      networks:
         - hadoopnet
    portainer:
      image: portainer/portainer
      command: -H unix:///var/run/docker.sock
      restart: always
      ports:
         - 9000:80
         - 8000:8000
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - portainer_data:/data
      networks:
         - hadoopnet
volumes:
    hadoop_namenode:
    hadoop_datanode:
    hadoop_historyserver:
    portainer_data:
networks:
    hadoopnet:
